# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: actions/upload-artifact
        versions:
          - 4.3.0
          - 4.3.1
      - dependency-name: "actions/*"
        update-types: -verion-update:semver-major
